routes.py
from flask import Blueprint, render_template, request, flash, session, redirect, url_for
from models.models import User, Housekeeper, Admin, Task
from extensions import db
from sqlalchemy.exc import SQLAlchemyError
from flask_mail import Mail, Message

main = Blueprint('main', __name__)  # routename= main

mail = Mail()

@main.route('/', methods=['GET'])
def home():
    return render_template("index.html")

@main.route('/getStarted', methods=['GET'])
def getStarted():
    return render_template("login-register.html")

@main.route('/register', methods=['POST'])
def register():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')
    confirm_password = request.form.get('confirm_password')
    user_type = request.form.get('user_type')

    if password != confirm_password:
        flash('Passwords do not match!')
        return redirect(url_for('main.home'))

    if user_type == 'user':
        new_user = User(email=email,name=name, password=password)
    else:
        new_housekeeper = Housekeeper(email=email,name=name, password=password)

    try:
        if user_type == 'user':
            new_user.save()
        else:
            new_housekeeper.save()
        flash('Registration successful! Please log in.')
    except:
        flash('Email already exists!')
        return redirect(url_for('main.home'))

    return redirect(url_for('main.home'))

@main.route('/login', methods=['POST'])
def login():
    email = request.form.get('email')
    password = request.form.get('password')
    user_type = request.form.get('user_type')

    if user_type == 'user':
        user = User.query.filter_by(email=email).first()
    elif user_type == 'housekeeper':
        user = Housekeeper.query.filter_by(email=email).first()
    elif user_type == 'admin':
        user = Admin.query.filter_by(email=email).first()

    if user and user.password == password:
        session['user_id'] = user.id
        session['user_type'] = user_type
        if user_type == 'user':
            return redirect(url_for('main.user_dashboard'))
        elif user_type == 'housekeeper':
            return redirect(url_for('main.housekeeper_dashboard'))
        elif user_type == 'admin':
            return redirect(url_for('main.admin_dashboard'))
    else:
        flash('Login failed! Check your credentials and try again.')
        return redirect(url_for('main.home'))

@main.route('/user_dashboard', methods=['GET'])
def user_dashboard():
    if 'user_id' in session and session.get('user_type') == 'user':
        user = User.query.filter_by(id=session['user_id']).first()
        task = Task()
        tasks = task.get_by_user_id(user_id=session['user_id'])
        housekeepers = Housekeeper.get_unassigned()
        return render_template("user_dashboard.html", user=user, tasks = tasks,housekeepers = housekeepers)
    else:
        return redirect(url_for('main.home'))

@main.route('/housekeeper_dashboard', methods=['GET'])
def housekeeper_dashboard():
    if 'user_id' in session and session.get('user_type') == 'housekeeper':
        housekeeper_id = session['user_id']
        housekeeper = Housekeeper.query.filter_by(id=session['user_id']).first()
        available_tasks = db.session.query(Task, User).join(User, Task.user_id == User.id).filter(Task.is_done == True).all()
        managed_tasks = Task.query.filter_by(housekeeper_id=housekeeper_id).all()

        print(housekeeper)

        return render_template("housekeeper_dashboard.html",housekeeper=housekeeper, available_tasks=available_tasks, managed_tasks=managed_tasks)
    else:
        return redirect(url_for('main.home'))

@main.route('/admin_dashboard', methods=['GET'])
def admin_dashboard():
    if 'user_id' in session and session.get('user_type') == 'admin':
        admin = Admin.query.filter_by(id=session['user_id']).first()
        task = Task()
        tasks = task.get_all()
        return render_template("admin_dashboard.html", admin=admin, tasks=tasks)
    else:
        return redirect(url_for('main.home'))

@main.route('/logout', methods=['GET'])
def logout():
    session.clear()
    return redirect(url_for('main.home'))

@main.route('/admin_update', methods=['POST'])
def admin_update():
    if 'user_id' in session and session.get('user_type') == 'admin':
        email = request.form.get('email')
        password = request.form.get('password')
        admin = Admin.query.filter_by(id=session['user_id']).first()

        if email:
            admin.email = email
        if password:
            admin.password = password
        
        try:
            admin.save()
            flash('Account updated successfully!')
        except:
            flash('Update failed. Please try again.')

        return redirect(url_for('main.admin_dashboard'))
    else:
        return redirect(url_for('main.home'))

@main.route('/admin_tasks', methods=['GET'])
def admin_tasks():
    if 'user_id' in session and session.get('user_type') == 'admin':
        tasks = Task.query.all()  # Ensure you have a Task model defined
        return render_template("admin_tasks.html", tasks=tasks)
    else:
        return redirect(url_for('main.home'))

@main.route('/create_task', methods=['POST'])
def create_task():
    if 'user_id' in session and session.get('user_type') == 'user':
        user_id = session['user_id']
        address = request.form.get('address')
        phone = request.form.get('phone')
        summary = request.form.get('summary')
        description = request.form.get('full_description')
        housekeeper_id = request.form.get('housekeeper_id')
        workinghours = request.form.get('workinghours')

        housekeeper = Housekeeper.get_by_id(housekeeper_id)
        price = housekeeper.priceperhour
        new_task = Task(
            user_id=user_id,
            housekeeper_id=housekeeper_id,  # or assign based on some logic
            housekeeper_name=housekeeper.name,
            workinghours = workinghours,
            address=address,
            phone=phone,
            summary=summary,
            description=description,
            price=price,
            is_done=False,
            is_taken = True
        )

        try:
            new_task.save()
            # Send email notification to the housekeeper
            housekeeper = Housekeeper.get_by_id(housekeeper_id)
            msg = Message('New Task Assigned',sender='noreply@example.com',recipients=[housekeeper.email])
            msg.body = f'Hello {housekeeper.name},\n\nYou have been assigned a new task. Details:\n\nSummary: {summary}\nDescription: {description}\nAddress: {address}\nPhone: {phone}\nPrice: {price}\n\nPlease log in to view the task.'
            mail.send(msg)

            flash('Task created successfully!', 'success')
        except SQLAlchemyError as e:
            # Flash the specific error message
            flash(f'Failed to create task due to a database error: {str(e)}', 'error')
        except Exception as e:
            # Flash any other errors
            flash(f'Failed to create task. Error: {str(e)}', 'error')

        return redirect(url_for('main.user_dashboard'))
    else:
        return redirect(url_for('main.home'))


@main.route('/update_user_account', methods=['POST'])
def update_user_account():
    if 'user_id' in session and session.get('user_type') == 'user':
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')
        user = User.query.filter_by(id=session['user_id']).first()

        if email:
            user.email = email
        if name:
            user.name = name
        if password:
            user.password = password
        
        try:
            user.save()
            flash('Account updated successfully!')
        except:
            flash('Update failed. Please try again.')

        return redirect(url_for('main.user_dashboard'))
    else:
        return redirect(url_for('main.home'))

@main.route('/update_task/<int:task_id>', methods=['GET', 'POST'])
def update_task(task_id):
    if 'user_id' in session and session.get('user_type') == 'user':
        task = Task.query.filter_by(id=task_id, user_id=session['user_id']).first()

        if request.method == 'POST':
            task.summary = request.form.get('description')
            task.description = request.form.get('full_description')
            task.address = request.form.get('address')
            task.phone = request.form.get('phone')
            task.price = request.form.get('price')
            task.save()

            flash('Task updated successfully!')
            return redirect(url_for('main.user_dashboard'))

        return render_template('update_task.html', task=task)
    else:
        return redirect(url_for('main.home'))

@main.route('/delete_task/<int:task_id>', methods=['GET'])
def delete_task(task_id):
    if 'user_id' in session and session.get('user_type') == 'user':
        task = Task.query.filter_by(id=task_id, user_id=session['user_id']).first()
        if task:
            db.session.delete(task)
            db.session.commit()
            flash('Task deleted successfully!')
        return redirect(url_for('main.user_dashboard'))
    else:
        return redirect(url_for('main.home'))
    

@main.route('/accept_task/<int:task_id>', methods=['GET'])
def accept_task(task_id):
    if 'user_id' in session and session.get('user_type') == 'housekeeper':
        task = Task.query.get_or_404(task_id)
        if task.is_taken:
            flash('This task has already been accepted by another housekeeper.')
            return redirect(url_for('main.housekeeper_dashboard'))
        
        task.is_taken = True
        task.housekeeper_id = session['user_id']
        try:
            db.session.commit()
            flash('Task successfully accepted!')
        except SQLAlchemyError as e:

templates/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block stylePic %} class='bg-pic' {% endblock %}
{% block content %}
<div class="container mt-5 bg-color p-4">
    <h1>Welcome to the Admin Dashboard</h1>

    <!-- Logout Button -->
    <a href="{{ url_for('main.logout') }}" class="btn btn-danger mb-3">Logout</a>

    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    
    <!-- Tabs for navigation -->
    <ul class="nav nav-tabs" id="adminTabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active" id="update-tab" data-bs-toggle="tab" href="#update" role="tab">Update Account</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="tasks-tab" data-bs-toggle="tab" href="#tasks" role="tab">View Tasks</a>
        </li>
    </ul>
    <div class="tab-content" id="adminTabsContent">
        <!-- Update Account Tab -->
        <div class="tab-pane fade show active" id="update" role="tabpanel" aria-labelledby="update-tab">
            <form method="post" action="{{ url_for('main.admin_update') }}">
                <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" value="{{admin.email}}" class="form-control" id="email" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>

        <!-- View Tasks Tab -->
        <div class="tab-pane fade" id="tasks" role="tabpanel" aria-labelledby="tasks-tab">
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th>Task ID</th>
                        <th>User ID</th>
                        <th>Housekeeper ID</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr>
                        <td>{{ task.id }}</td>
                        <td>{{ task.user_id }}</td>
                        <td>{{ task.housekeeper_id }}</td>
                        <td>{{ 'Completed' if task.is_done else 'Pending' }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/housekeeper_dashboard.html
{% extends "base.html" %}
{% block title %}Housekeeper Dashboard{% endblock %}
{% block stylePic %} class='bg-pic' {% endblock %}
{% block content %}
<div class="container mt-5 bg-color p-4">
    <h1>Welcome to Your Dashboard</h1>

    <!-- Logout Button -->
    <a href="{{ url_for('main.logout') }}" class="btn btn-danger mb-3">Logout</a>

    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <!-- Tabs for navigation -->
    <ul class="nav nav-tabs" id="housekeeperTabs" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active" id="tasks-tab" data-bs-toggle="tab" href="#tasks" role="tab">Completed Tasks</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="manage-tasks-tab" data-bs-toggle="tab" href="#manage-tasks" role="tab">Manage Tasks</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="update-account-tab" data-bs-toggle="tab" href="#update-account" role="tab">Update Account</a>
        </li>
    </ul>

    <div class="tab-content" id="housekeeperTabsContent">
        <!-- Available Tasks Tab -->
        <div class="tab-pane fade show active" id="tasks" role="tabpanel" aria-labelledby="tasks-tab">
            <table class="table mt-3" id="myTable">
                <thead>
                    <tr>
                        <th>User email</th>
                        <th>Summary</th>
                        <th>Description</th>
                        <th>Address</th>
                        <th>Price</th>
<!--                        <th>Actions</th>-->
                    </tr>
                </thead>
                <tbody>
                    {% for task,user in available_tasks %}
                    <tr>
                        <td>{{ user.email }}</td>
                        <td>{{ task.summary }}</td>
                        <td>{{ task.description }}</td>
                        <td>{{ task.address }}</td>
                        <td>{{ task.price }}</td>
<!--                        <td>-->
<!--                            <a href="{{ url_for('main.accept_task', task_id=task.id) }}" class="btn btn-success btn-sm">Accept</a>-->
<!--                        </td>-->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- Manage Tasks Tab -->
        <div class="tab-pane fade" id="manage-tasks" role="tabpanel" aria-labelledby="manage-tasks-tab">
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th>Task ID</th>
                        <th>Summary</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in managed_tasks %}
                    <tr>
                        <td>{{ task.id }}</td>
                        <td>{{ task.summary }}</td>
                        <td>{{ 'Completed' if task.is_done else 'Pending' }}</td>
                        <td>
                            <a href="{{ url_for('main.update_task_status', task_id=task.id) }}" class="btn btn-warning btn-sm">Change Status</a>
<!--                            <a href="{{ url_for('main.deny_task', task_id=task.id) }}" class="btn btn-danger btn-sm">Deny</a>-->
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- Update Account Tab -->
        <div class="tab-pane fade" id="update-account" role="tabpanel" aria-labelledby="update-account-tab">
            <form method="post" action="{{ url_for('main.update_housekeeper_account') }}">
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" value="{{ housekeeper.name }}" class="form-control" id="name" name="name" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" value="{{ housekeeper.email }}" class="form-control" id="email" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="priceperhour" class="form-label">Price per Hour</label>
                    <input type="number" value="{{ housekeeper.priceperhour }}" class="form-control" id="priceperhour" name="priceperhour" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <button type="submit" class="btn btn-primary">Update Account</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/login-register.html
{% extends "base.html" %}
{% block title %} HKMS - HomePage {% endblock %}
{% block stylePic %} class='bg-pic' {% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row ">
        <div class="col-md-6 offset-md-3 bg-color p-4">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="login-tab" data-bs-toggle="tab" data-bs-target="#login" type="button" role="tab" aria-controls="login" aria-selected="true">Login</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="register-tab" data-bs-toggle="tab" data-bs-target="#register" type="button" role="tab" aria-controls="register" aria-selected="false">Register</button>
                </li>
            </ul>
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="login" role="tabpanel" aria-labelledby="login-tab">
                    <form class="form-container mt-4" method="POST" action="{{ url_for('main.login') }}">
                        <div class="mb-3">
                            <label for="loginEmail" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="loginEmail" name="email" aria-describedby="emailHelp">
                        </div>
                        <div class="mb-3">
                            <label for="loginPassword" class="form-label">Password</label>
                            <input type="password" class="form-control" id="loginPassword" name="password">
                        </div>
                        <div class="mb-3">
                            <label for="userType" class="form-label">Login as</label>
                            <select class="form-select" id="userType" name="user_type">
                                <option value="user">User</option>
                                <option value="housekeeper">Housekeeper</option>
                                <option value="admin">Admin</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
                <div class="tab-pane fade" id="register" role="tabpanel" aria-labelledby="register-tab">
                    <form class="form-container mt-4" method="POST" action="{{ url_for('main.register') }}">
                        <div class="mb-3">
                            <label for="registerName" class="form-label">Name</label>
                            <input type="text" class="form-control" id="registerName" name="name" aria-describedby="nameHelp">
                        </div>
                        <div class="mb-3">
                            <label for="registerEmail" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="registerEmail" name="email" aria-describedby="emailHelp">
                        </div>
                        <div class="mb-3">
                            <label for="registerPassword" class="form-label">Password</label>
                            <input type="password" class="form-control" id="registerPassword" name="password">
                        </div>
                        <div class="mb-3">
                            <label for="registerConfirmPassword" class="form-label">Confirm Password</label>
                            <input type="password" class="form-control" id="registerConfirmPassword" name="confirm_password">
                        </div>
                        <div class="mb-3">
                            <label for="userType" class="form-label">Register as</label>
                            <select class="form-select" id="userType" name="user_type">
                                <option value="user">User</option>
                                <option value="housekeeper">Housekeeper</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/update_task.html
{% extends "base.html" %}
{% block title %}Update Task{% endblock %}
{% block stylePic %} class='bg-pic' {% endblock %}
{% block content %}
<div class="container mt-5 bg-color p-4">
    <h1>Update Task</h1>
    <form method="post" action="{{ url_for('main.update_task', task_id=task.id) }}">
        <div class="mb-3">
            <label for="description" class="form-label">Summary Description</label>
            <input type="text" class="form-control" id="description" name="description" value="{{ task.summary }}" required>
        </div>
        <div class="mb-3">
            <label for="full-description" class="form-label">Full Description</label>
            <textarea class="form-control" id="full-description" name="full_description" required>{{ task.description }}</textarea>
        </div>
        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <input type="text" class="form-control" id="address" name="address" value="{{ task.address }}" required>
        </div>
        <div class="mb-3">
            <label for="phone" class="form-label">Phone Number</label>
            <input type="text" class="form-control" id="phone" name="phone" value="{{ task.phone }}" required>
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price (RWF)</label>
            <input type="number" class="form-control" id="price" name="price" value="{{ task.price }}" required>
        </div>
        <button type="submit" class="btn btn-primary">Update Task</button>
        <a href="{{ url_for('main.user_dashboard') }}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/user_dashboard.html
{% extends "base.html" %}
{% block title %}User Dashboard{% endblock %}
{% block stylePic %} class='bg-pic' {% endblock %}
{% block content %}
<div class="container mt-5 p-3 bg-color">
    <h1>Welcome to Your Dashboard</h1>

    <!-- Logout Button -->
    <a href="{{ url_for('main.logout') }}" class="btn btn-danger mb-3">Logout</a>

    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

   <div class="row">
        <!-- <div class="col-md-5"> -->
            <!-- Tabs for navigation -->
            <ul class="nav nav-tabs" id="userTabs" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active" id="tasks-tab" data-bs-toggle="tab" href="#tasks" role="tab">My Tasks</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="create-task-tab" data-bs-toggle="tab" href="#create-task" role="tab">Create Task</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" id="update-account-tab" data-bs-toggle="tab" href="#update-account" role="tab">Update Account</a>
                </li>
            </ul>

            <div class="tab-content" id="userTabsContent">
                <!-- My Tasks Tab -->
                <div class="tab-pane fade show active" id="tasks" role="tabpanel" aria-labelledby="tasks-tab">
                    <table class="table mt-3" id="myTable">
                        <thead>
                            <tr>
                                <th>Task ID</th>
                                <th>HouseKeeper Name</th>
                                <th>Summary</th>
                                <th>Description</th>
                                <th>Working Hours</th>
                                <th>Price</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in tasks %}
                            <tr>
                                <td>{{ task.id }}</td>
                                <td>{{ task.housekeeper_name }}</td>
                                <td>{{ task.summary }}</td>
                                <td>{{ task.description }}</td>
                                <td>{{ task.workinghours if task.workinghours else '0' }} Hours</td>
                                <td>{{ task.price }}</td>
                                <td>{{ 'Completed' if task.is_done else 'Pending' }}</td>
                                {% if task.is_done is not true %}
                                <td>
<!--                                    <a href="{{ url_for('main.update_task', task_id=task.id) }}" class="btn btn-warning btn-sm">Edit</a>-->
                                    <a href="{{ url_for('main.delete_task', task_id=task.id) }}" class="btn btn-danger btn-sm">Delete</a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- Create Task Tab -->
                <div class="tab-pane fade" id="create-task" role="tabpanel" aria-labelledby="create-task-tab">
                    <form method="post" action="{{ url_for('main.create_task') }}">
                        <div class="mb-3">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" name="address" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone" class="form-label">Phone Number</label>
                            <input type="text" class="form-control" id="phone" name="phone" required>
                        </div>
                        <div class="mb-3">
                            <label for="summary" class="form-label">Summary Description</label>
                            <input type="text" class="form-control" id="summary" name="summary" required>
                        </div>
                        <div class="mb-3">
                            <label for="workinghours" class="form-label">Working Hours</label>
                            <input type="number" class="form-control" id="workinghours" name="workinghours" required>
                        </div>
                        <div class="mb-3">
                            <label for="full-description" class="form-label">Full Description</label>
                            <textarea class="form-control" id="full-description" name="full_description" required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="housekeeper_id" class="form-label">HouseKeeper</label>
                            <select class="form-control" id="housekeeper_id" name="housekeeper_id">
                                <option value="" selected>Select a HouseKeeper</option>
                                {% for housekeeper in housekeepers %}
                                    <option value="{{ housekeeper.id }}">{{ housekeeper.name }} : Price per Hour {{ housekeeper.priceperhour }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Create Task</button>
                    </form>
                </div>

                <!-- Update Account Tab -->
                <div class="tab-pane fade" id="update-account" role="tabpanel" aria-labelledby="update-account-tab">
                    <form method="post" action="{{ url_for('main.update_user_account') }}">
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" value="{{ user.name }}" class="form-control" id="name" name="name" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email address</label>
                            <input type="email" value="{{ user.email }}" class="form-control" id="email" name="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <button type="submit" class="btn btn-primary">Update Account</button>
                    </form>
                </div>
            </div>
        <!-- </div> -->
   </div>
</div>
{% endblock %}